

spring:
  #redis
  redis:
    host: localhost
#    password: admin
    port: 7001
    timeout: 10000
    jedis:
      pool:
        max-idle: 200
        min-idle: 300000
        max-active: 400
        max-wait: 10000

mifos-ussd:
  maximumUSSDSessionIdleAgeSeconds: 60
  clearIdleSessionsFixedDelay: 100
  menu:
    INITIAL_STATE:
      stateType: INPUT
      eventTrigger: MAIN_MENU_EVENT
    MAIN_MENU_STATE:
      stateType: CHOICE
      textTemplate: Welcome to mifos.\n1. Withdraw\n2. Transfer\n3. Loan\n4. Savings
      eventTriggerChoices:
        1: WITHDRAW_MENU_EVENT
        2: TRANSFER_MENU_EVENT
        3: LOAN_MENU_EVENT
        4: SAVINGS_MENU_EVENT
    WITHDRAW_MENU_STATE:
      stateType: INPUT
      textTemplate: Select account.<#list accounts as acc>\n${acc?counter}. Acc:${acc} </#list>
      eventTrigger: WITHDRAW
    ENTER_WITHDRAW_AMOUNT_STATE:
      stateType: INPUT
      textTemplate: Please enter amount to withdraw
    CONFIRM_WITHDRAW_AMOUNT_STATE:
      stateType: CHOICE
      textTemplate: Confirm to withdraw {{amount}}.\n1. Confirm\n2. Cancel
      eventTriggerChoices:
        1: WITHDRAW_STATE
        2: CANCEL_WITHDRAW_STATE
    WITHDRAW_STATE:
      stateType: TERMINATE
      textTemplate: with